### ISSUE TITLE
Support for split NAC and multi nac.

### ISSUE THREAD

**Issue by kjl13** [DVMProject/dvmhost#4]
I recommend the addition of split NAC and multi NAC(allows use of DVM project in community repeaters) to the DVM project.

**Comment by gatekeep** [comment]
Commit [34f8b04](https://github.com/DVMProject/dvmhost/commit/34f8b0407f92716bc05b0eea4b0b732bf5d238f8) adds split NAC support.

After review multi-NAC and $F7F NAC support is not currently feasible at this time due to the overall architecture of how P25 NIDs are handled, a change at this point would touch far too much of the codebase requiring quite extensive testing to ensure nothing is broken. At this time there will be no support for multi-NAC and $F7F.
